services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # network_mode: "host" 已被移除，以启用标准的容器间网络。

    volumes:
      # 挂载项目代码
      - .:/workspace:cached
      # 挂载宿主机的 SSH 配置 (只读)
      - ~/.ssh:/home/vscode/.ssh:ro

    # 保持容器持续运行
    command: sleep infinity

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  mysql-data:
