# 使用微软的通用开发镜像
FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
RUN brew install --cask netcat
RUN brew install --cask curl
RUN brew install --cask git
RUN brew install --cask jq
RUN brew install --cask yq
